from bs4 import BeautifulSoup
import re

html = '''

<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8" /><meta http-equiv="Content-Language" content="en" />
<meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=0, width=device-width"><meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>Best Construction Services in Uganda - List of Construction Services Uganda</title>
<meta name="description" content="Best Construction Services in Uganda. List of Best Construction Services in Uganda, Top Construction Services in Uganda, Construction Services Near Me, Best Construction Services." /><link rel="stylesheet" type="text/css" href="/css/main.min.css?v=542" />
<link rel="shortcut icon" href="https://www.yellow.ug/favs/y-96.png" type="image/png" sizes="96x96" type="image/png" /><link rel="manifest" href="/manifest/ugmanifest.json">
<link rel="apple-touch-icon" href="/favs/y/icon-192x192.png">
<meta name="msapplication-config" content="none" />
<meta name="theme-color" content="#7fc6c8">
<meta name="msapplication-navbutton-color" content="#7fc6c8">
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="preconnect" href="https://ajax.googleapis.com"><link rel="preconnect" href="https://maxcdn.bootstrapcdn.com"><link rel="preconnect" href="https://googleads.g.doubleclick.net">
<link rel="alternate" type="application/rss+xml" title="Uganda Business Directory Feed" href="/rss">
<link rel="amphtml" href="https://www.yellow.ug/category/construction-services?amp=1"><link rel="canonical" href="https://www.yellow.ug/category/construction-services" /><!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif]-->
<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', 'UA-32149495-37', 'auto');ga('send', 'pageview');ga('create', 'UA-9697326-3', 'auto', {'name': 'totalTracker'});ga('totalTracker.send', 'pageview');</script>
<meta property="og:image" content="https://www.yellow.ug/img/site/default-list.jpg?v=2" />
<meta property="fb:app_id" content="896691427028449" />
<script data-ad-client="ca-pub-3351151485848212" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" crossorigin="anonymous"></script><script>(adsbygoogle = window.adsbygoogle || []).push({google_ad_client: "ca-pub-3351151485848212",enable_page_level_ads: true});</script>
</head>
<body>
<a id="nav-top"></a>
<header>
<nav>
<a href="https://www.yellow.ug" title="Uganda Business Directory - Yellow Uganda" class="logo_link logo_yellow" style="background-image: url(/img/logos/yellow.png?v=26);">Uganda Business Directory - Yellow Uganda</a> <div class="s_box">
<form id="search_form" data-autocomplete-loaded="0" method="post" action="/uganda-business-search"><fieldset style="display:none;"><input type="hidden" name="_method" value="POST" /></fieldset>
<div class="input text"><input name="data[CompanySearch][query]" type="text" placeholder="Search for Companies or Services" autocorrect="off" autocomplete="off" maxlength="40" class="highlight" value="" id="CompanySearchQuery" /></div>
<div class="input text"><input name="data[CompanySearch][location]" type="text" placeholder="Location" autocorrect="off" autocomplete="off" maxlength="40" value="" id="CompanySearchLocation" /></div>
<a href="#" class="s_submit" aria-label="Search"><i class="fa fa-search" aria-hidden="true"></i></a>
<a href="/browse-business-directory" class="browse_submit">Browse Categories</a>
<input type="submit" class="hidden" value="Search" />
</form>
<a href="#" id="s_close" class="dm_close hidden"><i class="fa fa-window-close" aria-hidden="true"></i></a>
</div>
<a href="#" id="m_search_link" class="m_header_link m_visible" title="Companies Search"><i class="fa fa-search" aria-hidden="true"></i></a>
<div id="s_drop"></div>
<div class="userbox userbox_en">
<div id="userbox_menu">
<a href="/sign-in">Sign in</a> <a href="/create-business-listing" title="Add Business" class="add_business r_2px">Add Business</a> </div>
<a href="#" class="m_header_link m_menu_link" aria-label="Show navbar" data-ajaxload="0"><i class="fa fa-bars" aria-hidden="true"></i></a>
</div>
<div id="dm">
<div id="dm_in">
<div class="dm_nav"><a href="/sign-in" title="Sign in" class="add_business user_signin r_20px">Sign in</a><div class="dm_label"><b>Business Directory</b></div><a href="/">Uganda Business Directory</a><a href="/browse-business-directory">Browse Categories</a><a href="/browse-business-cities">Browse Locations</a><a href="/public-holidays">Public Holidays 2022</a><a href="/contact-us">Contact us</a><a href="/create-business-listing" class="add_business2 r_20px">+ Add Business</a><div class="dm_label"><b>Jobs</b></div><a href="/jobs">Jobs Uganda</a><a href="/jobs/accounting">Accounting Jobs</a><a href="/jobs/sales">Sales Jobs</a><a href="/jobs/all/type:internship">Internship Jobs</a><a href="/jobs/post-a-job" class="add_business2 r_20px">+ Post a Job</a><div class="dm_label"><b>Real Estate</b></div><a href="/real-estate">Real Estate in Uganda</a><a href="/real-estate/all">Available Properties</a><a href="/real-estate/list-property" class="add_business2 r_20px">+ LIST PROPERTY</a></div><br /><br />
</div>
<a href="#" id="userbox_close" class="dm_close" aria-label="Close navbar"><i class="fa fa-window-close" aria-hidden="true"></i></a></div>
<div id="topsocial" class="fb-like" data-href="https://www.yellow.ug" data-width="100" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>
</nav>
</header>
<div id="top">
<section>
<ul>
<li><a href="/jobs?utm_source=topjobs&utm_medium=topjobslink" title="Job Search Uganda"><b>Jobs</b></a></li>
<li><a href="/real-estate/all-properties?utm_source=topproperties&utm_medium=toppropertieslinks" title="Real Estate Uganda"><b>Real Estate</b></a></li>
<li><a href="/public-holidays?utm_source=topholidays&utm_medium=topholidayslinks" title="Public Holidays Uganda"><b>Public Holidays</b></a></li>
<li><a href="/bets/soccer-prediction" title="Soccer Prediction Uganda"><b>Soccer Prediction</b></a></li>
<li><a href="/" title="Uganda Business Directory"><b>Business Directory</b></a></li>
</ul>
</section>
</div>
<main>
<section>
<div class="tp"><ul itemscope itemtype="https://schema.org/BreadcrumbList"><li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><a href="/" itemprop="item"><span itemprop="name">Uganda</span></a><meta itemprop="position" content="1" /></li><li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><a href="/browse-business-directory" itemprop="item"><span itemprop="name">Categories</span></a><meta itemprop="position" content="2" /></li><li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><a href="/category/tradesmen-construction" itemprop="item"><span itemprop="name">Tradesmen & Construction</span></a><meta itemprop="position" content="3" /></li><li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><a href="/category/construction-services" itemprop="item"><span itemprop="name">Construction Services</span></a><meta itemprop="position" content="4" /></li></ul></div> <h1>Best Construction Services in Uganda</h1> <div id="page_text">Looking for <strong>Best Construction Services</strong> in Uganda? Find the list of Top Best Construction Services in Uganda on our business directory. Best Construction Services near me.</div>
<div id="filters" data-selected=".cat641">
<h5 class="r_2px"><a href="#">Filter by City <i class="fa fa-caret-down" aria-hidden="true"></i></a></h5>
<div class="cats m_hidden">
<input type="text" value="" placeholder="Search City" class="r_2px" data-cat="641-c" />
<ul>
<li><a href="/category/construction-services/city:kampala" class="city1">Kampala</a></li><li><a href="/category/construction-services/city:kira" class="city2">Kira</a></li><li><a href="/category/construction-services/city:gulu" class="city3">Gulu</a></li><li><a href="/category/construction-services/city:lira" class="city4">Lira</a></li><li><a href="/category/construction-services/city:mbale" class="city5">Mbale</a></li><li><a href="/category/construction-services/city:nansana" class="city6">Nansana</a></li><li><a href="/category/construction-services/city:jinja" class="city7">Jinja</a></li><li><a href="/category/construction-services/city:mbarara" class="city8">Mbarara</a></li><li><a href="/category/construction-services/city:entebbe" class="city9">Entebbe</a></li><li><a href="/category/construction-services/city:kasese" class="city10">Kasese</a></li>
</ul>
</div>
<h5 class="r_2px"><a href="#">Related Categories <i class="fa fa-caret-down" aria-hidden="true"></i></a></h5>
<div class="cats m_hidden"><ul>
<li><a href="/category/aluminium-openings" class="cat1335">Aluminium Openings</a><span>74</span></li><li><a href="/category/architectural-services" class="cat630">Architectural Services</a><span>209</span></li><li><a href="/category/building-materials" class="cat636">Building Materials</a><span>258</span></li><li><a href="/category/chemicals" class="cat1408">Chemicals</a><span>171</span></li><li><a href="/category/concrete" class="cat1546">Concrete</a><span>4</span></li><li><a href="/category/Construction" class="cat656">Construction </a><span>856</span></li><li><a href="/category/construction-equipment" class="cat640">Construction Equipment</a><span>506</span></li><li><a href="/category/construction-services" class="cat641">Construction Services</a><span>642</span></li><li><a href="/category/construction-training" class="cat642">Construction Training</a><span>10</span></li><li><a href="/category/decorators" class="cat643">Decorators</a><span>41</span></li><li><a href="/category/doors" class="cat1625">Doors</a><span>2</span></li><li><a href="/category/drywall" class="cat1549">Drywall</a><span>3</span></li><li><a href="/category/excavators" class="cat1550">Excavators</a><span>1</span></li><li><a href="/category/exterminating-and-disinfecting" class="cat1506">Exterminating and Disinfecting</a><span>1</span></li><li><a href="/category/fencing-and-fence-materials" class="cat1547">Fencing and Fence Materials</a><span>3</span></li><li><a href="/category/forestry" class="cat1627">Forestry</a><span>0</span></li><li><a href="/category/gardeners" class="cat644">Gardeners</a><span>11</span></li><li><a href="/category/glass-manufacturing" class="cat1509">Glass Manufacturing</a><span>0</span></li><li><a href="/category/handyman" class="cat1538">Handyman</a><span>2</span></li><li><a href="/category/landscaping" class="cat1463">Landscaping</a><span>9</span></li><li><a href="/category/locksmiths" class="cat649">Locksmiths</a><span>3</span></li><li><a href="/category/lumber" class="cat1545">Lumber</a><span>0</span></li><li><a href="/category/metals" class="cat1585">Metals</a><span>2</span></li><li><a href="/category/paving" class="cat1552">Paving</a><span>0</span></li><li><a href="/category/plumbers" class="cat1507">Plumbers</a><span>11</span></li><li><a href="/category/remodeling" class="cat1551">Remodeling</a><span>3</span></li><li><a href="/category/roofing" class="cat1536">Roofing</a><span>4</span></li><li><a href="/category/sandblasting" class="cat1543">Sandblasting</a><span>2</span></li><li><a href="/category/stone" class="cat1584">Stone</a><span>0</span></li><li><a href="/category/windows" class="cat1626">Windows</a><span>1</span></li>
</ul></div>
</div>
<div id="listings">
<div class="ad336">
<ins class="adsbygoogle asas" style="display:block" data-ad-client="ca-pub-3351151485848212" data-ad-slot="3758602228" data-max-num-ads=2 data-ad-format="rectangle"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({}); </script>
</div><div id="page_text_m">Looking for <strong>Best Construction Services</strong> in Uganda? Find the list of Top Best Construction Services in Uganda on our business directory. Best Construction Services near me.</div><div class="pages_container_top">We found <strong>642</strong> companies</div><div class="m_list_links m_visible"><a href="/category/construction-services?showmap=1" id="m_map_link"><i class="fa fa-map" aria-hidden="true"></i>&nbsp;&nbsp;Map</a></div><div class="company with_img g_0" id="cmap_0"><h4><a href="/company/39192/true-intelligence-technologies-inc" title="True Intelligence Technologies Inc.">True Intelligence Technologies Inc.</a></h4><div class="address">2711 Centerville Road, New Castle, DE</div><div class="details"><div class="desc">True Intelligence Technologies Inc. offers innovative web based construction management software and applications for making construction fast, simple, cost effective and efficient. Company's falgship...</div><a href="/company/39192/true-intelligence-technologies-inc" class="logo" title="True Intelligence Technologies Inc. Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/x/1385557428_65188.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/x/_1385557428_65188.jpg" alt="True Intelligence Technologies Inc." class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+9</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/39192/true-intelligence-technologies-inc" title="True Intelligence Technologies Inc. Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 3 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 1 <span>Products</span></div></a></div><div class="clear"></div><a href="#0" class="mapmarker" data-ltd="39.755018" data-lng="-75.626847" data-key="0" title="Company #1 Location on Map">1</a><div class="company_reviews"><div class="stars"></div><div class="rate">4.8</div><a href="/company/39192/true-intelligence-technologies-inc/reviews">5 Reviews</a></div></div>
<div class="company with_img g_0" id="cmap_1"><h4><a href="/company/40576/orbimaps-limited" title="ORBIMAPS LIMITED">ORBIMAPS LIMITED</a></h4><div class="address">Radiant House, Plot 20 Kampala Road, P.O.Box 2344 Kampala. Uganda, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">OrbiMaps Ltd specializes in providing professional Geographic Information Systems and Geo-database development, Remote Sensing, Land surveying, Digital Mapping, Valuation, Civil Engineering and Projec...</div><a href="/company/40576/orbimaps-limited" class="logo" title="ORBIMAPS LIMITED Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/k/1629467584-72-dynamaps-geomatics.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/k/_1629467584-72-dynamaps-geomatics.jpg" alt="ORBIMAPS LIMITED" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+7</b> &nbsp;Years with us</u><u class="v v4"><i class="fa fa-bolt" aria-hidden="true"></i> &nbsp;Updated</u></div><div class="cont"><a href="/company/40576/orbimaps-limited" title="ORBIMAPS LIMITED Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 1 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#1" class="mapmarker" data-ltd="0.385252854713493" data-lng="32.5878436057259" data-key="1" title="Company #2 Location on Map">2</a><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div><a href="/company/40576/orbimaps-limited/reviews">3 Reviews</a></div></div>
<div class="company with_img g_0" id="cmap_2"><h4><a href="/company/40861/excite-construction-limited" title="Excite Construction Limited">Excite Construction Limited</a></h4><div class="address">PLOT 19, ROBERT MUGABE ROAD P.O BOX 10455, KAMPALA, UGANDA, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">Excite Construction began in 2014 with the development of homes, and schools within the Kampala city. Today, Excite Construction Limited continues that same hardworking motivation that not only makes ...</div><a href="/company/40861/excite-construction-limited" class="logo" title="Excite Construction Limited Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/n/1476579685-26-excite-construction-limited.png"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/n/_1476579685-26-excite-construction-limited.png" alt="Excite Construction Limited" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+6</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/40861/excite-construction-limited" title="Excite Construction Limited Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 1 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 2 <span>Products</span></div></a></div><div class="clear"></div><a href="#2" class="mapmarker" data-ltd="0.328901391882654" data-lng="32.6229572296143" data-key="2" title="Company #3 Location on Map">3</a><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div><a href="/company/40861/excite-construction-limited/reviews">2 Reviews</a></div></div>
<div class="company company_ad"><ins class="adsbygoogle" style="display:block" data-ad-format="fluid" data-ad-layout-key="-ht+5+15-58+68" data-ad-client="ca-pub-3351151485848212" data-ad-slot="7479942841"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</div><div class="company with_img g_0" id="cmap_3"><h4><a href="/company/39978/by-express-construction-company-limited" title="By-express construction company limited">By-express construction company limited</a></h4><div class="address">kabalagala, kampala, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">for all construction services and agricultural supplies, by express construction started as a construction company which in july 2016 expanded to the agricultural sector too by registering a group of ...</div><a href="/company/39978/by-express-construction-company-limited" class="logo" title="By-express construction company limited Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/x/1470809750-16-by-express-construction-company-limited.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/x/_1470809750-16-by-express-construction-company-limited.jpg" alt="By-express construction company limited" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+8</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/39978/by-express-construction-company-limited" title="By-express construction company limited Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 1 <span>Products</span></div></a></div><div class="clear"></div><a href="#3" class="mapmarker" data-ltd="0.299655740314537" data-lng="32.5965937972069" data-key="3" title="Company #4 Location on Map">4</a><div class="company_reviews"><div class="stars"></div><div class="rate">4.5</div><a href="/company/39978/by-express-construction-company-limited/reviews">2 Reviews</a></div></div>
<div class="company with_img g_0" id="cmap_4"><h4><a href="/company/40426/design-world-ltd" title="DESIGN WORLD LTD">DESIGN WORLD LTD</a></h4><div class="address">Plot 1466 Church Rd; Kyaliwajjala, KIRA DIVISION, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">Design-World Ltd” [DW] is a manufacturer & supplier of premium Furniture & Household fittings including Doors, Windows, Kitchen cabinets, wardrobes and other building fittings & accessories. We also p...</div><a href="/company/40426/design-world-ltd" class="logo" title="DESIGN WORLD LTD Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/f/1575610777-73-design-world-ltd.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/f/_1575610777-73-design-world-ltd.jpg" alt="DESIGN WORLD LTD" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+7</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/40426/design-world-ltd" title="DESIGN WORLD LTD Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#4" class="mapmarker" data-ltd="0.385924043706423" data-lng="32.6396191120148" data-key="4" title="Company #5 Location on Map">5</a><div class="company_reviews"><div class="stars"></div><div class="rate">4.0</div><a href="/company/40426/design-world-ltd/reviews">1 Review</a></div></div>
<div class="company with_img g_0" id="cmap_5"><h4><a href="/company/40748/empire-group" title="Empire Group">Empire Group</a></h4><div class="address">Plot 425 Juuko Road, Kibuye, Kampala, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">Empire Group has expertise in all construction industry services including architectural, structural, mechanical and electrical drawing services also specializing in drafting, design and steel detaili...</div><a href="/company/40748/empire-group" class="logo" title="Empire Group Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/m/1469542568-47-empire-group.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/m/_1469542568-47-empire-group.jpg" alt="Empire Group" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+6</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/40748/empire-group" title="Empire Group Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#5" class="mapmarker" data-ltd="0.292944565009758" data-lng="32.5744945306275" data-key="5" title="Company #6 Location on Map">6</a><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div><a href="/company/40748/empire-group/reviews">1 Review</a></div></div>
<div class="company with_img g_0" id="cmap_6"><h4><a href="/company/40574/the-engineering-marksmen-ltd" title="The Engineering Marksmen Ltd">The Engineering Marksmen Ltd</a></h4><div class="address">Plazza Building Luzira, P.O.Box 8495 Kampala, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">The Engineering Marksmen Ltd is a Building and Civil engineering firm in Uganda. Founded in 2013, The Engineering Marksmen Ltd has continued to offer reliable and dependable building construction solu...</div><a href="/company/40574/the-engineering-marksmen-ltd" class="logo" title="The Engineering Marksmen Ltd Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/m/1660055616-34-the-engineering-marksmen-ltd.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/m/_1660055616-34-the-engineering-marksmen-ltd.jpg" alt="The Engineering Marksmen Ltd" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+7</b> &nbsp;Years with us</u><u class="v v4"><i class="fa fa-bolt" aria-hidden="true"></i> &nbsp;Updated</u></div><div class="cont"><a href="/company/40574/the-engineering-marksmen-ltd" title="The Engineering Marksmen Ltd Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 2 <span>Products</span></div></a></div><div class="clear"></div><a href="#6" class="mapmarker" data-ltd="0.3040108720770492" data-lng="32.64398574829105" data-key="6" title="Company #7 Location on Map">7</a><div class="company_reviews"><div class="stars"></div><div class="rate">4.0</div><a href="/company/40574/the-engineering-marksmen-ltd/reviews">1 Review</a></div></div>
<div class="company company_ad"><ins class="adsbygoogle" style="display:block" data-ad-format="fluid" data-ad-layout-key="-ht+5+15-58+68" data-ad-client="ca-pub-3351151485848212" data-ad-slot="7479942841"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</div><div class="company with_img g_0" id="cmap_7"><h4><a href="/company/39639/victorson-group" title="VICTORSON GROUP LLC.">VICTORSON GROUP LLC.</a></h4><div class="address">800m off,Entebbe Rd Ndeeje # 70635 Kampala Uganda., <a href="/location/wakiso" title="Companies in Wakiso" class="city56 b">Wakiso</a></div><div class="details"><div class="desc">Victorson Group is a provider of professional service solutions. Delivering service products to clients with our dedicated Professional personnel’s and working together with partners around the globe....</div><a href="/company/39639/victorson-group" class="logo" title="VICTORSON GROUP LLC. Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/c/1398520325_23638.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/c/_1398520325_23638.jpg" alt="VICTORSON GROUP LLC." class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+9</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/39639/victorson-group" title="VICTORSON GROUP LLC. Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 17 <span>Products</span></div></a></div><div class="clear"></div><a href="#7" class="mapmarker" data-ltd="0.217545938210617" data-lng="32.5488209724426" data-key="7" title="Company #8 Location on Map">8</a></div>
<div class="company with_img g_0" id="cmap_8"><h4><a href="/company/43548/trinnox-associates-ltd" title="Trinnox Associates Ltd">Trinnox Associates Ltd</a></h4><div class="address">Kamuli road, Kireka , <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">Best Civil and Construction engineering company in Uganda providing architectural designs , house construction, road maintenance and all services regarding houses</div><a href="/company/43548/trinnox-associates-ltd" class="logo" title="Trinnox Associates Ltd Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/n/1587993763-59-trinnox-associates-ltd.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/n/_1587993763-59-trinnox-associates-ltd.jpg" alt="Trinnox Associates Ltd" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u></div><div class="cont"><a href="/company/43548/trinnox-associates-ltd" title="Trinnox Associates Ltd Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div></a></div><div class="clear"></div><a href="#8" class="mapmarker" data-ltd="0.346785695764009" data-lng="32.6482814926394" data-key="8" title="Company #9 Location on Map">9</a><div class="company_reviews"><div class="stars"></div><div class="rate">4.0</div><a href="/company/43548/trinnox-associates-ltd/reviews">1 Review</a></div></div>
<div class="company with_img g_0" id="cmap_9"><h4><a href="/company/39974/global-link-investments-and-construction-co-ltd" title="Global Link Investments and Construction Co. Ltd">Global Link Investments and Construction Co. Ltd</a></h4><div class="address">Plot 13 Maruzi Road, <a href="/location/lira" title="Companies in Lira" class="city4 b">Lira</a></div><div class="details"><div class="desc">We are an engineering company, dealing in construction works and services. We supply and install solar systems for homes, schools, health centres, hospitals, farms and hotels. We offer expert advice o...</div><a href="/company/39974/global-link-investments-and-construction-co-ltd" class="logo" title="Global Link Investments and Construction Co. Ltd Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/f/1499661663-84-global-link-investments-and-construction-co-ltd.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/f/_1499661663-84-global-link-investments-and-construction-co-ltd.jpg" alt="Global Link Investments and Construction Co. Ltd" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+8</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/39974/global-link-investments-and-construction-co-ltd" title="Global Link Investments and Construction Co. Ltd Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#9" class="mapmarker" data-ltd="2.24016779446271" data-lng="32.8934419155121" data-key="9" title="Company #10 Location on Map">10</a><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div><a href="/company/39974/global-link-investments-and-construction-co-ltd/reviews">1 Review</a></div></div>
<div class="company with_img g_0" id="cmap_10"><h4><a href="/company/39606/propositum" title="EREKT Construction Company">EREKT Construction Company</a></h4><div class="address">Kampala Uganda, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">EXECUTIVE SUMMARY Erect Construction company is a construction company based in Kampala, Uganda specializing in construction of residential, commercial, industrial and any form of mixed use Architectu...</div><a href="/company/39606/propositum" class="logo" title="EREKT Construction Company Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/c/1444830744-88-erekt-construction-company.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/c/_1444830744-88-erekt-construction-company.jpg" alt="EREKT Construction Company" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+9</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/39606/propositum" title="EREKT Construction Company Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#10" class="mapmarker" data-ltd="0.361269042037043" data-lng="32.5948095401977" data-key="10" title="Company #11 Location on Map">11</a><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div><a href="/company/39606/propositum/reviews">1 Review</a></div></div>
<div class="company with_img g_0" id="cmap_11"><h4><a href="/company/39223/1-oxford-general-contractors-co-ltd" title="Oxford General Contractors Construction Company ">Oxford General Contractors Construction Company </a></h4><div class="address">Plot 794, Ggaba Road, Bunga &#40;Near Shell&#41;, Kampala Uganda., <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">Oxford General Contractors - A trustworthy company based in Uganda that will oversee your whole building project from start to finish.. We also deal in property sales and property rental management CA...</div><a href="/company/39223/1-oxford-general-contractors-co-ltd" class="logo" title="Oxford General Contractors Construction Company  Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/f/1389538289_89945.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/f/_1389538289_89945.jpg" alt="Oxford General Contractors Construction Company " class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+9</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/39223/1-oxford-general-contractors-co-ltd" title="Oxford General Contractors Construction Company  Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 3 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#11" class="mapmarker" data-ltd="0.258880542141164" data-lng="32.6270824518067" data-key="11" title="Company #12 Location on Map">12</a><div class="company_reviews"><div class="stars"></div><div class="rate">4.0</div><a href="/company/39223/1-oxford-general-contractors-co-ltd/reviews">1 Review</a></div></div>
<div class="company company_ad"><ins class="adsbygoogle" style="display:block" data-ad-format="fluid" data-ad-layout-key="-ht+5+15-58+68" data-ad-client="ca-pub-3351151485848212" data-ad-slot="7479942841"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</div><div class="company with_img g_0" id="cmap_12"><h4><a href="/company/42772/ibm-readymix-concrete-company-ltd-uganda-kampala" title="iBM ReadyMix Concrete Company Ltd (Uganda-Kampala)">iBM ReadyMix Concrete Company Ltd (Uganda-Kampala)</a></h4><div class="address">iBM ReadyMix Concrete Company Ltd &#40;Uganda&#45;Kampala&#41;, TEL: &#43;256781580278, &#43;256704032414, Email: info@ibmconcrete.com, WEBSITE: www.ibmconcrete.com, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">iBM READY-MIX CONCRETE COMPANY UGANDA-KAMPALA LTD iBM Ready-Mix Concrete Co. Ltd Uganda is a trusted supplier of quality ready mix concrete / premix-concrete to both the building and civil constructio...</div><a href="/company/42772/ibm-readymix-concrete-company-ltd-uganda-kampala" class="logo" title="iBM ReadyMix Concrete Company Ltd (Uganda-Kampala) Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/b/1541710438-11-ibm-readymix-concrete-company-ltd-uganda-kampala.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/b/_1541710438-11-ibm-readymix-concrete-company-ltd-uganda-kampala.jpg" alt="iBM ReadyMix Concrete Company Ltd (Uganda-Kampala)" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+4</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/42772/ibm-readymix-concrete-company-ltd-uganda-kampala" title="iBM ReadyMix Concrete Company Ltd (Uganda-Kampala) Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#12" class="mapmarker" data-ltd="0.31427167852414" data-lng="32.5824076524308" data-key="12" title="Company #13 Location on Map">13</a></div>
<div class="company with_img g_0" id="cmap_13"><h4><a href="/company/42310/ibm-steel-metal-fabrication-welding-company-uganda" title="IBM STEEL METAL FABRICATION WELDING COMPANY UGANDA">IBM STEEL METAL FABRICATION WELDING COMPANY UGANDA</a></h4><div class="address">Pilkington Road Kampala, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">IBM STEEL & METAL FABRICATION COMPANY UGANDA LTD offers; A. Steel fabrication services- Uganda B. Metal & Steel Welding services - Uganda C. Steel Erection services- Uganda D. Steel-buildings works - ...</div><a href="/company/42310/ibm-steel-metal-fabrication-welding-company-uganda" class="logo" title="IBM STEEL METAL FABRICATION WELDING COMPANY UGANDA Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/c/1526147766-45-ibm-steel-metal-engineering-uganda-kampala-ltd.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/c/_1526147766-45-ibm-steel-metal-engineering-uganda-kampala-ltd.jpg" alt="IBM STEEL METAL FABRICATION WELDING COMPANY UGANDA" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+4</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/42310/ibm-steel-metal-fabrication-welding-company-uganda" title="IBM STEEL METAL FABRICATION WELDING COMPANY UGANDA Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#13" class="mapmarker" data-ltd="0.316526212960956" data-lng="32.5849229592774" data-key="13" title="Company #14 Location on Map">14</a></div>
<div class="company with_img g_0" id="cmap_14"><h4><a href="/company/42521/kasthew-demolishersexcavators-company-ugandaaa" title="KASTHEW DEMOLISHERS &amp; EXCAVATORS COMPANY UGANDAAA">KASTHEW DEMOLISHERS &amp; EXCAVATORS COMPANY UGANDAAA</a></h4><div class="address">KASTHEW Demolishers &amp; Excavators Company Uganda, &#43;256781580278, &#43;256704032414 EMAIL: kasthew@gmail.com, info@kasthew&#45;construction.com www.kasthew&#45;construction.com KAMPALA CITY &#45; UGANDA &#40;EAST AFRICA&#41;, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">KASTHEW DEMOLISHERS & EXCAVATION CONTRACTORS UGANDA-KAMPALA LTD TEL/WATSUP: +256704032414, +256781580278, Email: kasthew@gmail.com OUR SERVICES: 1. Building Demolishing services Uganda 2. Site Excavat...</div><a href="/company/42521/kasthew-demolishersexcavators-company-ugandaaa" class="logo" title="KASTHEW DEMOLISHERS &amp; EXCAVATORS COMPANY UGANDAAA Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/j/1533901640-63-kasthew-demolishers-excavators-company-ugandaaa.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/j/_1533901640-63-kasthew-demolishers-excavators-company-ugandaaa.jpg" alt="KASTHEW DEMOLISHERS & EXCAVATORS COMPANY UGANDAAA" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+4</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/42521/kasthew-demolishersexcavators-company-ugandaaa" title="KASTHEW DEMOLISHERS &amp; EXCAVATORS COMPANY UGANDAAA Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#14" class="mapmarker" data-ltd="0.316869530470064" data-lng="32.5849229592774" data-key="14" title="Company #15 Location on Map">15</a></div>
<div class="company with_img g_0" id="cmap_15"><h4><a href="/company/42543/kmc-land-excavatorsgrading-contractor-uganda" title="KMC LAND EXCAVATORS &amp; GRADING CONTRACTOR UGANDA">KMC LAND EXCAVATORS &amp; GRADING CONTRACTOR UGANDA</a></h4><div class="address">Pilkington Road, Kampala, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">KMC LAND EXCAVATORS, LAND-GRADING & SITE-CLEARING, DEMOLISHING CONTRACTORS UGANDA-KAMPALA LTD TEL/WATSUP: +256704032414, +256781580278, Email: kasthew@gmail.com, info@kasthew-construction.com, OUR SER...</div><a href="/company/42543/kmc-land-excavatorsgrading-contractor-uganda" class="logo" title="KMC LAND EXCAVATORS &amp; GRADING CONTRACTOR UGANDA Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/g/1534856994-82-kmc-land-excavators-grading-contractor-uganda.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/g/_1534856994-82-kmc-land-excavators-grading-contractor-uganda.jpg" alt="KMC LAND EXCAVATORS & GRADING CONTRACTOR UGANDA" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+4</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/42543/kmc-land-excavatorsgrading-contractor-uganda" title="KMC LAND EXCAVATORS &amp; GRADING CONTRACTOR UGANDA Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#15" class="mapmarker" data-ltd="0.314344156237148" data-lng="32.582410103975" data-key="15" title="Company #16 Location on Map">16</a></div>
<div class="company with_img g_0" id="cmap_16"><h4><a href="/company/41684/water-brick-borehole-drilling-company-uganda" title="Water brick borehole drilling company uganda">Water brick borehole drilling company uganda</a></h4><div class="address">Good Shade Plaza Opposite fire Brigade, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">Water Brick is one of borehole drilling companies in Uganda WATER BRICK BOREHOLE DRILLING COMPANY UGANDA LIMITED WATER BRICK BOREHOLE DRILLING COMPANY UGANDA LIMITED WATER BRICK BOREHOLE DRILLING COMP...</div><a href="/company/41684/water-brick-borehole-drilling-company-uganda" class="logo" title="Water brick borehole drilling company uganda Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/d/1502957114-40-water-brick-borehole-drilling-company-uganda.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/d/_1502957114-40-water-brick-borehole-drilling-company-uganda.jpg" alt="Water brick borehole drilling company uganda" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+5</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/41684/water-brick-borehole-drilling-company-uganda" title="Water brick borehole drilling company uganda Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#16" class="mapmarker" data-ltd="0.309375570788402" data-lng="32.58041203022" data-key="16" title="Company #17 Location on Map">17</a></div>
<div class="company with_img g_0" id="cmap_17"><h4><a href="/company/41768/antioch-uganda-limited" title="Antioch Uganda Limited">Antioch Uganda Limited</a></h4><div class="address">4th Street Industrial Area, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">Antioch Uganda Limited works on various projects involving final finishing for residential, commercial, industrial, recreational, hospital, education and museum buildings. Whether yours is a modest fa...</div><a href="/company/41768/antioch-uganda-limited" class="logo" title="Antioch Uganda Limited Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/a/1506165483-27-antioch-uganda-limited.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/a/_1506165483-27-antioch-uganda-limited.jpg" alt="Antioch Uganda Limited" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+5</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/41768/antioch-uganda-limited" title="Antioch Uganda Limited Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#17" class="mapmarker" data-ltd="0.3233956" data-lng="32.6040844" data-key="17" title="Company #18 Location on Map">18</a></div>
<div class="company with_img g_0" id="cmap_18"><h4><a href="/company/40334/glam-builders-limited" title="Glam Builders Limited">Glam Builders Limited</a></h4><div class="address">Basement &amp; Ground floor Glam House, Bugerere road, Mukono Town. P.O. Box 505 Mukono,, <a href="/location/mukono" title="Companies in Mukono" class="city16 b">Mukono</a></div><div class="details"><div class="desc">Glam Builders’ Vision is helping customers get quality building materials and Engineering services at competitive prices. Glam Builders’ Store is located at Ground and First floor Glam House, Bugerere...</div><a href="/company/40334/glam-builders-limited" class="logo" title="Glam Builders Limited Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/e/1441549939-44-glam-builders-limited.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/e/_1441549939-44-glam-builders-limited.jpg" alt="Glam Builders Limited" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+7</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/40334/glam-builders-limited" title="Glam Builders Limited Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#18" class="mapmarker" data-ltd="0.361144356501947" data-lng="32.7524408698082" data-key="18" title="Company #19 Location on Map">19</a></div>
<div class="company with_img g_0" id="cmap_19"><h4><a href="/company/39866/halai-holdings-lrd" title="Halai Holdings Ltd">Halai Holdings Ltd</a></h4><div class="address">Plot 71&#45;72 Semawata Road&#45; Ntinda, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">HHL was incorporated in the year 2000, and has over the years grown into a one stop shop for Construction materials, machinery and Technical Support. We have various earth moving machinery both for lo...</div><a href="/company/39866/halai-holdings-lrd" class="logo" title="Halai Holdings Ltd Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/k/1410015233_33272.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/k/_1410015233_33272.jpg" alt="Halai Holdings Ltd" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+8</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/39866/halai-holdings-lrd" title="Halai Holdings Ltd Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#19" class="mapmarker" data-ltd="0.343084923770694" data-lng="32.7956968664737" data-key="19" title="Company #20 Location on Map">20</a></div>
<div class="company company_ad"><ins class="adsbygoogle" style="display:block" data-ad-format="fluid" data-ad-layout-key="-ht+5+15-58+68" data-ad-client="ca-pub-3351151485848212" data-ad-slot="7479942841"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</div><div class="company with_img g_4" id="cmap_20"><h4><a href="/company/43649/ibm-building-construction-material-supplier-uganda" title="IBM Building Construction Material Supplier Uganda">IBM Building Construction Material Supplier Uganda</a></h4><div class="address">IBM Building &amp; Construction Material Supply Company Uganda Kampala, TEL &#43;256781580278, &#43;256704032414, https://www.ibmbuildingmaterials.co.ug,, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">IBM Building & Construction Material Supply Company Uganda is a leading supplier of Aggregate Stones, Hardcore Stones, Cement, Lake-Sand, Timber & Wood, Readymix Concrete, etc in Uganda - Kampala, for...</div><a href="/company/43649/ibm-building-construction-material-supplier-uganda" class="logo" title="IBM Building Construction Material Supplier Uganda Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/x/1599514312-28-ibm-building-construction-material-supplier-uganda.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/x/_1599514312-28-ibm-building-construction-material-supplier-uganda.jpg" alt="IBM Building Construction Material Supplier Uganda" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u></div><div class="cont"><a href="/company/43649/ibm-building-construction-material-supplier-uganda" title="IBM Building Construction Material Supplier Uganda Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#20" class="mapmarker" data-ltd="0.314226418809396" data-lng="32.5823139175415" data-key="20" title="Company #21 Location on Map">21</a></div>
<div class="company with_img g_0" id="cmap_21"><h4><a href="/company/42007/orlandoh-general-engineering-and-supplies-ltd" title="ORLANDOH GENERAL ENGINEERING AND SUPPLIES LTD">ORLANDOH GENERAL ENGINEERING AND SUPPLIES LTD</a></h4><div class="address">KIBULI, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">WE DEAL IN FABRICATIONS OF STEEL TANKS , PRODUCT PIPE LINE, STEEL STRUCTURES, PUMP INSTALLATIONS , MECHANICAL PLUMBING INDUSTRIAL AND DOMESTIC. WE CONSTRUCT FUEL FILLING STATIONS, FUEL DEPOTS,ETC.</div><a href="/company/42007/orlandoh-general-engineering-and-supplies-ltd" class="logo" title="ORLANDOH GENERAL ENGINEERING AND SUPPLIES LTD Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/h/1516889132-10-orlandoh-general-engineering-and-supplies-ltd.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/h/_1516889132-10-orlandoh-general-engineering-and-supplies-ltd.jpg" alt="ORLANDOH GENERAL ENGINEERING AND SUPPLIES LTD" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+5</b> &nbsp;Years with us</u><u class="v v4"><i class="fa fa-bolt" aria-hidden="true"></i> &nbsp;Updated</u></div><div class="cont"><a href="/company/42007/orlandoh-general-engineering-and-supplies-ltd" title="ORLANDOH GENERAL ENGINEERING AND SUPPLIES LTD Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#21" class="mapmarker" data-ltd="0.289053891883437" data-lng="32.5975257260254" data-key="21" title="Company #22 Location on Map">22</a></div>
<div class="company with_img g_4" id="cmap_22"><h4><a href="/company/43691/pakast-technical-services-limited" title="PAKAST TECHNICAL SERVICES LIMITED">PAKAST TECHNICAL SERVICES LIMITED</a></h4><div class="address">Plot/Block , 236/3186 No, Jinja Road Highway, Bweyogerere, Kampala, Uganda. , <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">PAKAST TECHNICAL SERVICES LIMITED has ventured in Geophysical and Hydrogeological surveys, Water well drilling, Coring and Geotechnical with services that meet the international standards, using advan...</div><a href="/company/43691/pakast-technical-services-limited" class="logo" title="PAKAST TECHNICAL SERVICES LIMITED Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/h/1634162262-55-pakast-technical-services-limited.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/h/_1634162262-55-pakast-technical-services-limited.jpg" alt="PAKAST TECHNICAL SERVICES LIMITED" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u></div><div class="cont"><a href="/company/43691/pakast-technical-services-limited" title="PAKAST TECHNICAL SERVICES LIMITED Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#22" class="mapmarker" data-ltd="0.353643492232661" data-lng="32.6696895584106" data-key="22" title="Company #23 Location on Map">23</a></div>
<div class="company with_img g_0" id="cmap_23"><h4><a href="/company/42901/q-semmy-enterprises" title="Q-Semmy Enterprises">Q-Semmy Enterprises</a></h4><div class="address">P.O BOX 1945,Lira,Uganda, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">Q-Semmy Enterprises is a Ugandan registered business that provides services and solutions in ICT,Electrical Services,Electronics and Communications Consultancy with Refrigeration and Air-conditioning ...</div><a href="/company/42901/q-semmy-enterprises" class="logo" title="Q-Semmy Enterprises Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/s/1548939116-81-q-semmy-enterprises.png"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/s/_1548939116-81-q-semmy-enterprises.png" alt="Q-Semmy Enterprises" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+4</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/42901/q-semmy-enterprises" title="Q-Semmy Enterprises Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#23" class="mapmarker" data-ltd="0.332147147933115" data-lng="32.6255208749268" data-key="23" title="Company #24 Location on Map">24</a></div>
<div class="company g_0" id="cmap_24"><h4><a href="/company/7725/the-depo-ltd" title="The Depo Ltd">The Depo Ltd</a></h4><div class="address">Plot 2A Old PortBell Road, P.O. Box 11099, Uganda, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u></div><div class="cont"><a href="/company/7725/the-depo-ltd" title="The Depo Ltd Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 2 <span>Photos</span></div></a></div><div class="clear"></div><a href="#24" class="mapmarker" data-ltd="0.319800802529291" data-lng="32.6006332039833" data-key="24" title="Company #25 Location on Map">25</a><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div><a href="/company/7725/the-depo-ltd/reviews">1 Review</a></div><a href="/company/7725/the-depo-ltd" class="m_company_link" title="The Depo Ltd Business Page"><i class="fa fa-angle-right" aria-hidden="true"></i></a></div>
<div class="company with_img g_0" id="cmap_25"><h4><a href="/company/42527/kastur-construction-ltd" title="KASTUR CONSTRUCTION LTD">KASTUR CONSTRUCTION LTD</a></h4><div class="address">KAMULI ROAD, KIREKA, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">Kastur Construction Company was established in 1996 and is a general contractor offering construction services in terms of Site Analysis, Feasibility Studies, Preliminary Design Studies, Permit/Zoning...</div><a href="/company/42527/kastur-construction-ltd" class="logo" title="KASTUR CONSTRUCTION LTD Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/z/1544697761-63-kastur-construction-ltd.png"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/z/_1544697761-63-kastur-construction-ltd.png" alt="KASTUR CONSTRUCTION LTD" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+4</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/42527/kastur-construction-ltd" title="KASTUR CONSTRUCTION LTD Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 3 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#25" class="mapmarker" data-ltd="0.359418441633648" data-lng="32.6401114004076" data-key="25" title="Company #26 Location on Map">26</a></div>
<div class="company with_img g_0" id="cmap_26"><h4><a href="/company/42686/techno-relief-services-u-ltd" title="Techno Relief Services (U) Ltd">Techno Relief Services (U) Ltd</a></h4><div class="address">5th street industrial area, beside fresh dairy , can city warehouse , kampala , uganda , <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">Techno Was Established in the year 1987 with a purpose to be involved in the supplies of humanitarian aid and relief supplies of goods and services by responding promptly to emergency situations arisi...</div><a href="/company/42686/techno-relief-services-u-ltd" class="logo" title="Techno Relief Services (U) Ltd Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/s/1538811304-52-techno-relief-services-u-ltd.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/s/_1538811304-52-techno-relief-services-u-ltd.jpg" alt="Techno Relief Services (U) Ltd" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+4</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/42686/techno-relief-services-u-ltd" title="Techno Relief Services (U) Ltd Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#26" class="mapmarker" data-ltd="0.319575527907936" data-lng="32.610974033988" data-key="26" title="Company #27 Location on Map">27</a></div>
<div class="company with_img g_0" id="cmap_27"><h4><a href="/company/43144/vodo-engineering-ltd" title="Vodo Engineering Ltd">Vodo Engineering Ltd</a></h4><div class="address">First Floor, BIFRO House, Sir Apollo Kaggwa Road, P.O.BOX 11368, Kampala, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">A leading company dedicated in water supply, Environmental management, Energy solutions, project management and consulting services; committed to global efforts to improving quality of life/ service a...</div><a href="/company/43144/vodo-engineering-ltd" class="logo" title="Vodo Engineering Ltd Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/a/1565292928-62-vodo-engineering-ltd.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/a/_1565292928-62-vodo-engineering-ltd.jpg" alt="Vodo Engineering Ltd" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+3</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/43144/vodo-engineering-ltd" title="Vodo Engineering Ltd Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#27" class="mapmarker" data-ltd="0.32976152805191" data-lng="32.6061319335938" data-key="27" title="Company #28 Location on Map">28</a></div>
<div class="company with_img g_0" id="cmap_28"><h4><a href="/company/43133/design-sense-kampala" title="Design Sense Kampala">Design Sense Kampala</a></h4><div class="address">Tuarus Towers Naalya, <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">We are a team that comprise of admins, architects, interior & landscape designers, gardeners, skilled laborers, semi-skilled laborers and casual laborers who are dedicated to provide the services of I...</div><a href="/company/43133/design-sense-kampala" class="logo" title="Design Sense Kampala Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/j/1564376385-95-j-flower-com-ltd.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/j/_1564376385-95-j-flower-com-ltd.jpg" alt="Design Sense Kampala" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+3</b> &nbsp;Years with us</u><u class="v v4"><i class="fa fa-bolt" aria-hidden="true"></i> &nbsp;Updated</u></div><div class="cont"><a href="/company/43133/design-sense-kampala" title="Design Sense Kampala Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 3 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 3 <span>Products</span></div></a></div><div class="clear"></div><a href="#28" class="mapmarker" data-ltd="0.3688981954112275" data-lng="32.64079700249936" data-key="28" title="Company #29 Location on Map">29</a></div>
<div class="company with_img g_0" id="cmap_29"><h4><a href="/company/41744/icecomm-technologies" title="ICECOMM TECHNOLOGIES">ICECOMM TECHNOLOGIES</a></h4><div class="address">P.O. BOX 6850 Kyambogo rd Banda , <a href="/location/kampala" title="Companies in Kampala" class="city1 b">Kampala</a></div><div class="details"><div class="desc">We are a technology company registered in Uganda For COMPUTING NETWORKING, WEB TECHNOLOGY, CCTV , GPS, BIOMEDICAL AND CONSTRUCTIONS SERVICES</div><a href="/company/41744/icecomm-technologies" class="logo" title="ICECOMM TECHNOLOGIES Business Page"><span itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><meta itemprop="url" content="https://www.yellow.ug/img/ug/c/1504965320-34-icecomm-technologies.jpg"><img src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/ug/c/_1504965320-34-icecomm-technologies.jpg" alt="ICECOMM TECHNOLOGIES" class="lazy-img r_3px" width="80" height="80"></a></div><div class="cont"><u class="v"><i class="fa fa-check" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+5</b> &nbsp;Years with us</u></div><div class="cont"><a href="/company/41744/icecomm-technologies" title="ICECOMM TECHNOLOGIES Business Page"><div class="s"><i class="fa fa-phone" aria-hidden="true"></i><span>Phone</span></div><div class="s"><i class="fa fa-envelope" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" aria-hidden="true"></i> 4 <span>Photos</span></div><div class="s"><i class="fa fa-rocket" aria-hidden="true"></i> 1 <span>Products</span></div></a></div><div class="clear"></div><a href="#29" class="mapmarker" data-ltd="0.344876352574191" data-lng="32.6332247257233" data-key="29" title="Company #30 Location on Map">30</a></div>
<div class="ad336_b">
<ins class="adsbygoogle asas" style="display:block" data-ad-client="ca-pub-3351151485848212" data-ad-slot="8959911556" data-max-num-ads=3 data-ad-format="rectangle"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({}); </script>
</div><div class="pages_container"><span class="pages_current">1</span><a href="/category/construction-services/2" class="pages_no">2</a><a href="/category/construction-services/3" class="pages_no">3</a><span class="pages_gap">...</span><a href="/category/construction-services/22" class="pages_no">22</a><a href="/category/construction-services/2" class="pages_arrow" rel="next">&#8594;</a> <div class="total"><strong>642</strong> companies</div></div><div class="suggest"><h6>Didn't find what you were looking for?</h6><div class="text">Tell us what is missing</div><br /><a href="/create-business-listing" class="blue_button">Add Business</a><br /><br /><h6>Do you like this list?</h6><div class="text">Share the link with others:</div><br /><a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.yellow.ug%2Fcategory%2Fconstruction-services&amp;utm_source=list_share" rel="noopener" target="_blank" title="Share the List on Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a><a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=https%3A%2F%2Fwww.yellow.ug%2Fcategory%2Fconstruction-services&amp;utm_source=list_share" rel="noopener" target="_blank" title="Share the List on Linkedin"><i class="fa fa-linkedin" aria-hidden="true"></i></a><a href="https://twitter.com/home?status=Awesome list on Uganda Business Directory. https%3A%2F%2Fwww.yellow.ug%2Fcategory%2Fconstruction-services&amp;utm_source=list_share" rel="noopener" target="_blank" title="Share the List on Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a><div class="clear"></div></div><h6>Most searched categories</h6><br /><div class="tags"><a href="/category/Construction" title="">Construction Companies in Uganda</a><a href="/category/secondary-schools/city:kampala" title="">Secondary Schools in Kampala</a><a href="/category/primary-schools/city:kampala" title="">Primary Schools in Kampala</a><a href="/category/beauty-salons/city:kampala" title="">Salons in Kampala</a><a href="/category/cleaning" title="">Cleaning Companies in Uganda</a><a href="/category/cosmetics" title="">Cosmetics Shops in Uganda</a><a href="/category/plastic-products" title="">Plastic Companies in Uganda</a><a href="/category/pharmacies" title="">List of Pharmacies in Uganda</a><a href="/category/driving-schools" title="">Driving Schools in Uganda</a><a href="/category/logistics" title="">Logistics Companies in Uganda</a><a href="/category/modeling-agencies" title="">Modeling Agencies in Uganda</a></div><div class="clear"></div></div>
<div id="mapslider_con" class="m_hidden">
<div id="mapslider">
<div id="companiesmap" class="gm_canvas gm_slider" data-autoshow="0" data-map-ltd="1.373333" data-map-lng="32.290275" data-map-key="AIzaSyC14UbPK8yB5woz-smPDU4hOZSEd6WlpeU" data-map-zoom="13">
<a href="#" id="show_map">Show Map</a>
</div>
</div>
</div>
<div class="clear"></div>
</section>
</main>
<div id="m_map" class="gm_canvas fullscreen hidden"></div>
<div id="loading"><i class="fa fa-cog fa-spin fa-3x fa-fw"></i></div>
<div id="fb-root"></div>
<a href="#nav-top" id="back_to_top">BACK TO TOP&nbsp;&nbsp;<i class="fa fa-angle-double-up" aria-hidden="true"></i></a>
<footer>
<section>
<div class="footer_box">
<h6>Links</h6>
<ul>
<li><a href="/browse-business-directory">Browse Categories</a></li>
<li><a href="/browse-business-cities">Browse Locations</a></li>
<li><a href="/jobs">Jobs in Uganda</a></li>
<li><a href="/international-business-directories-map">Our Global Network</a></li>
<li><a href="/public-holidays">Public Holidays in Uganda</a></li>
<li><a href="/bets/soccer-prediction">Soccer Prediction</a></li>
<li><a href="/real-estate">Real Estate in Uganda</a></li>
</ul>
</div>
<div class="footer_box">
<h6>Users</h6>
<ul>
<li><a href="/create-business-listing">Add Business</a></li><li><a href="/contact-us/remove:yes" rel="nofollow">Remove Company</a></li><li><a href="/sign-in">Sign in</a></li><li><a href="/contact-us">Contact us</a></li>
</ul>
</div>
<div class="footer_box footer_categories">
<h6>Main Categories</h6>
<ul>
<li><a href="/category/logistics">Logistics companies</a></li><li><a href="/category/travel-agents">Travel agencies</a></li><li><a href="/category/Construction">Construction companies</a></li><li><a href="/category/cleaning">Cleaning companies</a></li><li><a href="/category/information-technology">IT companies</a></li><li><a href="/category/adventist-schools">Insurance companies</a></li> </ul>
</div>
<div class="footer_box">
<h6>Database</h6>
<ul id="ss"><li><span>41,914</span>Companies</li><li><span>8,948</span>Photos</li><li><span>2,039</span>Reviews</li><li><span>5,456</span>Products</li></ul>
</div>
<div class="clear"></div>
<div class="social" id="bottom_fb_likes"><h6>People Like Us</h6><div class="fb-like" data-href="https://www.yellow.ug" data-width="" data-layout="button_count" data-action="like" data-size="large" data-share="true"></div></div>
<div class="social">
<div class="clear"></div>
<h6>Follow Us</h6>
<a href="https://www.facebook.com/ugandailoveyou" rel="noopener" target="_blank" aria-label="Facebook Fan Page"><i class="fa fa-facebook" aria-hidden="true"></i></a><a href="https://twitter.com/UgandaYellow" rel="noopener" target="_blank" aria-label="Twitter Page"><i class="fa fa-twitter" aria-hidden="true"></i></a><a href="https://www.linkedin.com/company/uganda-business-directory" rel="noopener" target="_blank" aria-label="Linkedin Page"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
</div>
<div id="international"><h6>Our Global Network</h6><ul><li><a href="https://www.yellosa.co.za" rel="noopener">Companies in South Africa</a></li><li><a href="https://www.ghanayello.com" rel="noopener">Companies in Ghana</a></li><li><a href="https://www.businesslist.com.ng" rel="noopener">Companies in Nigeria</a></li><li><a href="/international-business-directories-map" rel="nofollow">See All <i class="fa fa-long-arrow-right" aria-hidden="true"></i></a></li></ul></div>
<div id="copyright">
By continuing past this page, you agree to our <a href="/terms-of-use" rel="nofollow, noindex">Terms of use</a>, <a href="/cookies-policy" rel="nofollow, noindex">Cookies policy</a>, <a href="/privacy-policy" rel="nofollow, noindex">Privacy policy</a>.
&copy; 2009 - 2022 Yellow Uganda <small>(PRO3)</small>
</div>
</section>
</footer><script>['https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js','/js/main.min.js?v=542'].forEach(function(src) {var script = document.createElement('script');script.src = src;script.async = false;document.head.appendChild(script);});</script>
</body>
</html>
'''

soup = BeautifulSoup(html, 'html.parser')
title = soup.find_all(class_ = '')
for i in soup.find_all('div', class_='address').text:
    print(i)

# nos = re.findall(r'\d{3}\d{3}\d{6}', title)
# nn = list(map(int, nos))
#print(title)

