# Generated by Django 4.1.1 on 2022-10-03 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_remove_votesmodel_type_votesmodel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesmodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 16, 9, 42, 545188)),
        ),
    ]
