# Generated by Django 4.1.1 on 2022-10-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0004_alter_votesmodel_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesmodel',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
